### ISSUE TITLE
关于宝塔或者其他含有nginx的环境

### ISSUE THREAD

**Issue by flewsea** [cugxuan/gonelist-doc#1]
可以建议用户配置个伪静态
```
location /

    {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8000;

    }
```
对小白用户来说更简单一些

**Comment by cugxuan** [comment]
> 可以建议用户配置个伪静态
> 
> ```
> location /
> 
>     {
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_pass http://127.0.0.1:8000;
> 
>     }
> ```
> 
> 对小白用户来说更简单一些

这个 nginx 配置在宝塔什么地方配置呢，可以给个截图么。因为我这儿没有宝塔的环境。谢谢！

**Comment by flewsea** [comment]
![20201119112230](https://user-images.githubusercontent.com/4075883/99617160-a85c2880-2a59-11eb-96f7-b7edb9beda81.png)
红框旁边数字代表点击顺序

**Comment by cugxuan** [comment]
> ![20201119112230](https://user-images.githubusercontent.com/4075883/99617160-a85c2880-2a59-11eb-96f7-b7edb9beda81.png)
> 红框旁边数字代表点击顺序

感谢，这个需求伪静态和反向代理都可以实现，我之后把内容更新到文档，把你加到 [gonelist-doc 致谢](https://gonelist-doc.cugxuan.cn/#/thank?id=gonelist-doc)，最近比较忙，12 月初再统一更新文档吧。

**Comment by cugxuan** [comment]
> ![20201119112230](https://user-images.githubusercontent.com/4075883/99617160-a85c2880-2a59-11eb-96f7-b7edb9beda81.png)
> 红框旁边数字代表点击顺序

这个伪静态里面 host 不用改吗。如果使用二级域名的话，应该改对应的 host 吧？如果主站域名直接用来挂载 gonelist 的话应该就像你这么设置了吧。

**Comment by flewsea** [comment]
这里的host只是把当前用户访问时，头部的host转发给gonelist，如果gonelist上对域名有要求的话，应该改成对应的

**Comment by cugxuan** [comment]
OK，明白
